import type { Metadata } from 'next';
import './globals.css';
import Navbar from '~/components/Navbar';
import Footer from '~/components/Footer';
import { StoreProvider } from '~/context/StoreContext';
import { fetchProducts } from '~/lib/api';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default async function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    const products = await fetchProducts();

    return (
        <html lang="en">
            <body className="flex h-screen flex-col bg-gray-100 text-gray-900 antialiased">
                <StoreProvider initialProducts={products}>
                    <Navbar />
                    <main className="container mx-auto grow p-4">
                        {children}
                    </main>
                    <Footer />
                </StoreProvider>
            </body>
        </html>
    );
}
