import type { Metadata } from 'next';
import './globals.css';
import Navbar from '~/components/Navbar';
import Footer from '~/components/Footer';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className="flex h-screen flex-col bg-gray-100 text-gray-900 antialiased">
                <Navbar />
                <main className="container mx-auto grow p-4">{children}</main>
                <Footer />
            </body>
        </html>
    );
}
